cities/urls.py
from django.urls import path

from cities.views import (
    CityListView,
    CityDetailView,
    CityUpdateView,
    CityCreateView,
    CityDeleteView,
)


urlpatterns = [
    # path('', home, name='home'),
    path("", CityListView.as_view(), name="home"),
    path("detail/<int:pk>/", CityDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", CityUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", CityDeleteView.as_view(), name="delete"),
    path("add/", CityCreateView.as_view(), name="create"),
]

routes/models.py
from django.db import models
from cities.models import City


class Route(models.Model):
    name = models.CharField(
        max_length=50, unique=True, verbose_name="Название маршрута"
    )
    travel_times = models.PositiveSmallIntegerField(
        verbose_name="Общее время в пути")
    from_city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        related_name="route_from_city_set",
        verbose_name="Из какого города",
    )
    to_city = models.ForeignKey(
        "cities.City",
        on_delete=models.CASCADE,
        related_name="route_to_city_set",
        verbose_name="В какой город",
    )
    trains = models.ManyToManyField("trains.Train",
                                    verbose_name="Список поездов")

    def __str__(self):
        return (
            f"Маршрут из города {self.from_city} в город"
            f" {self.to_city}  с номером {self.name}"
        )

    class Meta:
        verbose_name = "Маршрут"
        verbose_name_plural = "Маршруты"
        ordering = ["name"]

templates/about.html
{% extends 'base.html' %}
 {% block title %}
 <title>About project</title>
 {% endblock %}
 {% block content %}
 <h1>Дорогу пи да го гу</h1>
 {% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url%}
{% url 'cities:create' as cities_create_url%}
{% url 'trains:home' as trains_home_url%}
{% url 'trains:create' as trains_create_url%}
{% url 'list' as route_list%}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

      {% block title %}{% endblock %}

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light  container" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Hi, {{ request.user }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item {% if request.path == cities_home_url %}active {% endif %}">
          <a class="nav-link"
             aria-current="page" href="{% url 'cities:home' %}">Города</a>
        </li>
        <li class="nav-item {% if request.path == trains_home_url %}active {% endif %}">
          <a class="nav-link" href="{% url 'trains:home' %}">Поезда</a>
        </li>
        <li class="nav-item" {% if request.path == route_list%}active {% endif %}>
          <a class="nav-link" href="{% url 'list' %}">Маршруты</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown
        {% if request.path == cities_create_url or request.path == trains_create_url%}active {% endif %}
        ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Добавить
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a></li>
            <li><a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a></li>

          </ul>

        </li>
       {% else %}
            <li class="nav-item">
                <a class="nav-link disabled" href="">Добавить</a>
            </li>
            {% endif %}
      {% if user.is_authenticated %}<li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
        </li>
      {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
          </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Регистрация</a>
          </li>
      {% endif %}



      </ul>
    </div>
  </div>
</nav>
  <div class="container">
      <div class="row">
          <div class="col-md-8 mx-auto my-4">
              {% if messages %}

                    {% for message in messages %}

                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

                              </button>

                            </div>
                            {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                              {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

                              </button>
                            </div>
                         {% endif %}



                    {% endfor %}

              {% endif %}
          </div>
      </div>
  </div>
  <div class="container">
  {% block content %}{% endblock %}
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  <script>
  $(document).ready(function() {
    $('.js-example-basic-single').select2();
    $('.js-example-basic-multiple').select2();
});
  </script>
  </body>
</html>

templates/form.html
<div class="row">
        <div class="col-md-4">
             <form action="{{ action }}" method="post"> {% csrf_token %}
     {{ form.as_p }}
                 <button type="submit" class="btn btn-primary">{{ button }}</button>

     </form>
        </div>
     </div>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>hi {{name}}</h1>
{% endblock %}